### ISSUE TITLE
dataset = np.load('../data/interim/earthquakes_jp.npz')

### ISSUE THREAD

**Issue by BaiLiping** [Rose-STL-Lab/DeepSTPP#1]
Hi, would it be possible to make the earthquake data folder available? Just want to try out the tutorial. Thanks

**Comment by BaiLiping** [comment]
I think all you have to do is to share the google drive folder link. I would then make a hyperlink towards your folder. Thanks.

**Comment by BaiLiping** [comment]
i have downloaded the data, but the format is different from the one you used for this set of code. Can you pls share the earthquake and covid data via google drive? thanks a lot.

**Comment by BaiLiping** [comment]
The covid data still has issue.

**Comment by BaiLiping** [comment]
can you share the google folder? just the covid data.

**Comment by madziejm** [comment]
Can you please kindly share the data in either S3 or Google Drive?
Many thanks!
